trigger:
-   master

variables:
    azureSubscription: 'subscription test env'
    webAppName: 'cryptomanager-server'

stages:
-   stage: Build
    displayName: Build stage

    jobs:
    -   job: Build
        displayName: Build
        pool:
            vmImage: windows-latest

        steps:

        -   task: mattlabrum.build-task.custom-build-task.downloadsSecureFile@0
            displayName: 'Download appsettings from library file secrets'
            inputs:
                fileInput: secrets.json
                targetPath: CryptoManager.Server/CryptoManager.WebApi/
                targetName: appsettings.json

        -   task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
                command: restore
                projects: '**/*.csproj'

        -   task: DotNetCoreCLI@2
            displayName: Build
            inputs:
                projects: '**/*.csproj'
                arguments: '--configuration $(BuildConfiguration)'

        -   task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
                command: test
                projects: '**/*Test/*.csproj'
                arguments: '--collect "Code coverage"'

        -   task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
                command: publish
                arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

        -   task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
            inputs:
                PathtoPublish: '$(build.artifactstagingdirectory)'

-   stage: Test_deployment
    displayName: Test deployment
    jobs:

    -   template: azure-deploy.yml
        parameters:
            environment: 'test'
            azureSubscription: $(azureSubscription)
            webAppName: $(webAppName)

-   stage: Prod_deployment
    displayName: Prod deployment
    jobs:

    -   template: azure-deploy.yml
        parameters:
            environment: 'prod'
            azureSubscription: $(azureSubscription)
            webAppName: $(webAppName)